### ISSUE TITLE
Memory usage quite high (factor 25)

### ISSUE THREAD

**Issue by stefan-reich** [bobbylight/RText#26]
When I load a 40 MB text file in RText, I get a 1GB Java VM...

Probably not easy to improve?

Many greetings

**Comment by bobbylight** [comment]
Sorry I'm replying almost a year late - yes, probably not easy to improve.  It might be the case that turning off code folding will help.  It might be worth even having an option to automatically disable code folding if files are over a certain size for this very reason.

**Comment by stefan-reich** [comment]
Ah, OK... yes, makes sense, I can try that. Haven't tried big files since then. Thanks

**Comment by bobbylight** [comment]
@stefan-reich, I know this was over a year ago, but do you know if this is still an issue?  There is now code in place that turns off code folding if the file size is greater than a certain threshold (which is configurable in the Options dialog).

**Comment by stefan-reich** [comment]
Oh, ah, yeah I think it's all good. Who uses sources that big... ^^ Many greetings
