### ISSUE TITLE
Can't build (com.fifesoft.rtext:fife.common:3.0.2-SNAPSHOT not found)

### ISSUE THREAD

**Issue by kosivantsov** [bobbylight/RText#44]
I get this error when I try to build:
`org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.fifesoft.rtext:fife.common:3.0.2-SNAPSHOT.`

**Comment by bobbylight** [comment]
Apologies, I must have been fetching that dependency out of my local maven repo.  A build should work now, as I've published a 3.0.2-SNAPSHOT to the Sonatype snapshots repo:

https://oss.sonatype.org/content/repositories/snapshots/com/fifesoft/rtext/fife.common/3.0.2-SNAPSHOT/
