### ISSUE TITLE
Cannot compile on eclipse

### ISSUE THREAD

**Issue by ntprintf** [bobbylight/RText#54]
The RTech editor is very great. I would like to build it on eclipse to add more feature.

I can compile using the gradle command line.

`./gradlew build installDist`

But on eclipse It's seem to be problem with the lib. conflig.

the import code below 
`import org.xml.sax.Attributes;
import org.xml.sax.InputSource;
import org.xml.sax.helpers.DefaultHandler;
.....
import javax.swing.*;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;`

The eclipse said ...
`The package org.xml.sax is accessible from more than one module: <unnamed>, java.xml`

I found that the file `xml-apis.14.0.1.jar` , `xml-apis-ext-1.3.04.jar` conflig with java.xml module from the JDK itself. 

Please suggest the way on the eclipse or orther idr for build it.

-------
I use JDK 14  from 'https://adoptopenjdk.net/' , eclipse 2021-3

Best regards,

**Comment by bobbylight** [comment]
Sounds like a configuration issue.  I'm not familiar with Eclipse; I build from IntelliJ and the command line.  I'd suggest doing a Google earch and see if anything matches your situation, for example:

https://stackoverflow.com/questions/55571046/eclipse-is-confused-by-imports-accessible-from-more-than-one-module
