### ISSUE TITLE
Build fails on OpenSuSE Leap 15.2 with openjdk-16

### ISSUE THREAD

**Issue by jlturriff** [bobbylight/RText#56]
After upgrading my OpenSuSE Leap 15 (x86_64) system to openjdk 16 (default in OpenSuSE is 11) and downloading RText, running ./gradlew build installDist fails with 'Could not resolve com.fifesoft.rtext:fife.common:3.1.1.'
I have attached debugging output.
[gradlewBuild.log](https://github.com/bobbylight/RText/files/6680953/gradlewBuild.log)

**Comment by bobbylight** [comment]
You may have just pulled at a bad time when fife.common and RText were out of sync.  There were fairly recent changes for gradle's concepts of a Java library vs. app, as well as migrating from Java 11 to 14 as the minimum runtime.  RText's latest [now pulls FifeCommon 4.0.0](https://github.com/bobbylight/RText/blob/master/build.gradle#L20); could you pull the latest and try again?

**Comment by jlturriff** [comment]
Sorry for the delay; I bricked my machine trying to isolate a new GPU card over the weekend, and just got it rebuilt.

I decided to jump from my distro's default of openjdk-11 right to **jdk-16.0.1** (the latest); it might have something to do with my results. :-)

I was able to build the program successfully, but there are run-time errors, and what got built is unusable because the menu doesn't seem to want to work.  I'll attach a screen-shot and an error log.

[RText.log.tar.gz](https://github.com/bobbylight/RText/files/6712967/RText.log.tar.gz)
[RTextScreen1](https://user-images.githubusercontent.com/7597215/123356642-b4e3ba80-d52d-11eb-88d2-2456383f6d55.png)

**Comment by bobbylight** [comment]
Thanks. The most recent release was in Java 14 so there may be issues with 16.  I'll have to take a look. As a shot on the dark, what happens if you delete the ~/.rtrxt folder and restart to take the default for all options?

**Comment by jlturriff** [comment]
Renaming ~/.rtext had no effect.  I should add that the menu items and icons below them are invisible until I run my cursor over them; the close button, though invisible, does work.

Now that I know how Oracle's jdks install into my distro (they end up in an entirely different place than where the distro's jdks go), I can try it with jdk-14 as well (if I can remember how update-alternatives works :-) ).

**Comment by jlturriff** [comment]
Right now I'm having fun with **update-alternatives** and **gradle**, which don't seem to be getting along.  I've installed **JDK-14** alongside **JDK-16**, and I'm able to switch between them with update-alternatives --config java, but I'm getting
**ERROR: JAVA_HOME is set to an invalid directory: /usr/java/jdk-14.0.2/bin/java**
when I run **./gradlew build installDist**.
Might I mention that I already had Gradle installed from my distro's repositories, but your installer insists on installing its own?  Why is that?

**Comment by jlturriff** [comment]
Possibly this is the root of the gradle problem:
https://stackoverflow.com/questions/22307516/gradle-finds-wrong-java-home-even-though-its-correctly-set

**Comment by bobbylight** [comment]
Re: grade being downloaded, that's the way the gradle wrapper works. It's designed that way so the build always uses the same version of gradle (it gets downloaded and cached).

That's unfortunately the second issue I've read about now where gradle has Java issues. The last one was older versions of grade not working with Java 14 when it was new (I think) due to heavy jvm structural changes on Oracle's part.

**Comment by bobbylight** [comment]
Closing this as we now require Java 17 and Gradle 7.6 to build, and builds appear to be working across all environments.
