### ISSUE TITLE
JRE issue from 3+

### ISSUE THREAD

**Issue by andika207** [bobbylight/RText#84]
I don't understand the following message.
2.63 seems to be the last version that runs fine.

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/k5xqJ5tD/screenshot-6.png' border='0' alt='screenshot-6'/></a>

**Comment by bobbylight** [comment]
What version of Windows are you using? Is it 32-bit or 64-bit? It might be the case that you're on 32-bit Windows XP (judging from the screenshot) and RText currently only comes with a 64-bit build.

**Comment by bobbylight** [comment]
Closing as this appears to be due to a 32-bit OS. Please reopen if this is not the case!
